xcodeproj 'OmniaPush Spec'
workspace '../OmniaPush'
inhibit_all_warnings!

target :OmniaPushTests, :exclusive => true do
  platform :ios, '6.0'
  pod 'Kiwi/XCTest'
  pod 'OmniaPush', :path => '../'
end
