xcodeproj 'OmniaPush Spec'
workspace '../OmniaPush'
inhibit_all_warnings!

def import_pods
  pod 'Kiwi', 
  pod 'OmniaPush', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOS Tests'
  import_pods
end
